version: '3'

services:
  database:
    build: ./database
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://backend:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data: